#!/bin/bash
#
# $1 is the current phase. INIT, WARMUP, RUNNING, STOP
# $2 is the current run number.
# $3 is the maximum run number.
# $4 is the current load value.
# $5 is the arguments that the user put in PRIME_MONITOR_ARGS in the sfs_rc file
#
#
echo $1 $2 $3 $4 $5  >> /tmp/my_monitor_out.txt
exit
